<?php
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$description = $config->getConfigValue('payment/paywisepayment/description');
?>

<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $(document).on("click","#paywisepayment", function() {
          var description = '<?= /* @noEscape */$description; ?>';
          $("input:radio").change(function () {
            if ($("#paywisepayment").is(":checked")) {
              $('.paywise').html(description);
            } else {
              $('.paywise').html('');
            }
          });
        });
    });
</script>